steps:
  - name: node:10.15.1
    entrypoint: yarn
    args: ["install"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["add", "firebase-tools"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["build"]
    env:
      - 'CONTENTFUL_SPACE_ID=$_SPACE_ID'
      - 'CONTENTFUL_ACCESS_TOKEN=$_ACCESS_TOKEN'
  - name: "node:10.15.1"
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "mcac-contentful", "--token", "$_TOKEN"]
